name: Appium CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Download Payfazz APK
        run: curl https://api.codemagic.io/artifacts/913d0ab9-7b61-442d-bff0-a2682d4014f2/4a486cc9-2d5a-4fd3-a804-97ba7ccc6de2/PF-staging-3.7.2-debug.apk -o payfazz-staging.apk
      - name: Run Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          emulator-build: 7425822
          script: adb install payfazz-staging.apk
