name: Appium CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Download Payfazz APK
        run: curl https://api.codemagic.io/artifacts/6a4e70a5-7398-42e1-b89c-c467faf3d578/afd249b1-9513-40fa-92e7-e8ab3ad76e63/PF-staging-3.7.2-debug.apk -o ./payfazz-staging.apk
      - name: Run Android emulator
        uses: reactivecircus/android-emulator-runner@v2.17.0
        with:
          api-level: 29
          emulator-build: 6110076
          arch: x86_64
          profile: Pixel 3
          script: ls -ltr && adb install -t payfazz-staging.apk
