name: Appium CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-11.0
    steps:
      - name: Run Android emulator
        uses: reactivecircus/android-emulator-runner@v2.17.0
        with:
          api-level: 29
          script: adb devices
