name: Appium CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Run Android emulator
        uses: reactivecircus/android-emulator-runner@v2.17.0
        with:
          api-level: 29
          emulator-build: 6110076
          script: adb devices
